### ISSUE TITLE
Support php-cs-fixer 3

### ISSUE THREAD

**Issue by RobinHoutevelts** [elyby/php-code-style#11]
Hello,

I came across this repository from https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3653 

I wanted to try out some of these fixers but noticed this package is pinned to the previous mayor version of `php-cs-fixer`.

Would it be possible to update this package so it works with the current version of `php-cs-fixer`?

**Comment by erickskrauch** [comment]
Hi.
Yes, definitely! It's long overdue to add support for version 3 of the PHP-CS-Fixer. I will try to do ASAP.

**Comment by erickskrauch** [comment]
Just a quick update: the job is done but I have no idea how to fix tests. Since PHP-CS-Fixer 3 doesn't come with the `AbstractFixerTestCase` class, so I can't fix tests for custom fixers. They should work, but you know, you can't be solid without tests.

**Comment by erickskrauch** [comment]
@RobinHoutevelts, hi! Sorry for the long wait. I finally managed to upgrade the code base to PHP-CS-Fixer 3. The new tag isn't released yet, but you can try it with the next command:

```sh
composer require --dev "ely/php-code-style:dev-master#137a898 as 0.4.0-dev"
```

You might also want to add `-w` or even `-W` flag to update related dependencies.
