### ISSUE TITLE
Split this repository

### ISSUE THREAD

**Issue by erickskrauch** [elyby/php-code-style#16]
This repository contains both coding style for Ely.by related projects and custom fixers, that might be useful to the PHP community itself. The issue https://github.com/elyby/php-code-style/issues/15 raised the problem, that keeping the up-to-date PHP-CS-Fixer version might not allow users of the custom fixers to use this package at all.

So the solution is simple: split this repository into two. Keep this repository with Ely.by coding style and a separate repository with fixers only.

**Comment by SleepWalker** [comment]
Hooray 🎉
